<?php
// --- Phase 1: Initialize and Process ---
require_once '../db.php';
require_once '../partials/delivery_header.php';

// -- Security: Access Control --
if (!isset($_SESSION['user_id']) || !isset($_SESSION['user_role_name']) || $_SESSION['user_role_name'] !== 'Delivery Person') {
    echo "<div class='alert alert-danger'>Access Denied. Please <a href='login.php'>login</a> to continue.</div>";
    require_once '../partials/footer.php';
    exit();
}

// --- Prepare Data for QR Code ---
// We will encode the user's ID and username into a JSON string.
// JSON is a structured and future-proof way to store data in a QR code.
$qr_data = [
    'user_id'  => $_SESSION['user_id'],
    'username' => $_SESSION['username'] // Assuming you store username in session upon login
];
// We need the username in the session. Let's update the login logic to include it.
// For now, let's fetch it if it's not there.
if (!isset($_SESSION['username'])) {
    $stmt = $conn->prepare("SELECT username FROM users WHERE user_id = ?");
    $stmt->bind_param("i", $_SESSION['user_id']);
    $stmt->execute();
    $result = $stmt->get_result()->fetch_assoc();
    $_SESSION['username'] = $result['username'];
    $qr_data['username'] = $result['username'];
}

// Convert the PHP array to a JSON string to be used by JavaScript.
$qr_data_json = json_encode($qr_data);

?>

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6 col-xl-4">

            <div class="card shadow-lg text-center">
                <div class="card-header bg-info text-dark">
                    <h4 class="mb-0"><i class="bi bi-person-vcard-fill"></i> My Digital ID Card</h4>
                </div>
                <div class="card-body p-4">
                    
                    <!-- This is the placeholder where the QR code will be generated -->
                    <div id="qrcode" class="d-flex justify-content-center mb-4"></div>

                    <h5 class="card-title"><?php echo htmlspecialchars($_SESSION['user_full_name']); ?></h5>
                    <p class="card-text text-muted"><?php echo htmlspecialchars($_SESSION['username']); ?></p>
                    
                    <hr>

                    <p class="mt-3">
                        Present this QR code to the Godown Keeper for attendance scanning.
                    </p>
                </div>
            </div>

        </div>
    </div>
</div>

<?php
require_once '../partials/footer.php';
?>

<!-- Include the QR Code generation library from a CDN -->
<script src="https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js"></script>

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Get the placeholder element where the QR code will be rendered.
    const qrcodeContainer = document.getElementById('qrcode');

    // Retrieve the JSON data string that was securely generated by PHP.
    // When scanned, the QR code will contain this exact string: e.g., '{"user_id":15,"username":"delivery"}'
    const dataToEncode = '<?php echo $qr_data_json; ?>';

    if (qrcodeContainer && dataToEncode) {
        // Create a new QRCode object
        new QRCode(qrcodeContainer, {
            text: dataToEncode,
            width: 200,
            height: 200,
            colorDark: "#000000",
            colorLight: "#ffffff",
            correctLevel: QRCode.CorrectLevel.H // High error correction
        });
    }
});
</script>